### ISSUE TITLE
impossible to use more than 310 channels

### ISSUE THREAD

**Issue by mattbeghin** [p3root/SJ-DMX#1]
when sending more than 310 channels (256+chunk size) it was writing again on the first channels. please apply this patch and thanks for the project !

[PATCH] Bug fix: only first 310 channels were working, if sending
 more there was flickering on first channels

---

 src/SJDMXU1/usbio.c | 4 +---
 1 file changed, 1 insertion(+), 3 deletions(-)

diff --git a/src/SJDMXU1/usbio.c b/src/SJDMXU1/usbio.c
index fa57124..2288ee5 100644
--- a/src/SJDMXU1/usbio.c
+++ b/src/SJDMXU1/usbio.c
@@ -324,14 +324,12 @@ int sendShowJockeyDeviceBuf(struct ShowJockeyDevice *dev, unsigned char *buffer,
     unsigned char *writeBuffer = buffer;

```
 unsigned char *bulkBuffer = (unsigned char*)malloc(maxPacketSizeOut);
```
-    unsigned char bulkPos[2];
  
   int bulkDataSize = maxPacketSizeOut - 2;
  
   while(leftWriteSize > 0) {
       memset(bulkBuffer, 0, maxPacketSizeOut);
-        *bulkPos = alreadyWrittenSize;
-        memcpy(bulkBuffer, bulkPos, 2);
- ```
     memcpy(bulkBuffer, &alreadyWrittenSize, 2);
  
   if(leftWriteSize > bulkDataSize) {
       writeSize = bulkDataSize;
  ```
  ## 
  
  2.3.5

**Comment by p3root** [comment]
could you send me a pull request pls?

**Comment by peternewman** [comment]
This was fixed in https://github.com/p3root/SJ-DMX/pull/2 wasn't it?

**Comment by p3root** [comment]
hey!

I am sorry, I don't work on this library anymore. I don't have access to a showjockey usb adapter anyway. I can't support you with the issue.

Patrik

**Comment by peternewman** [comment]
Thanks @p3root , no worries, I was merely pointing out I think @mattbeghin had provided the PR requested, and so this issue could indeed be fixed.

Someone ported the code into OLA a while back https://github.com/OpenLightingProject/ola/pull/1147, and I just ended up here while looking at something else (initially worrying we didn't have a fix for this issue in our code).
